const tokens = {
  color: {
    background: {
      primary: "#22875b",          // Deep green for main section background
      secondary: "#f4f7fa",        // Very light gray / white paper background
      Pink: "#f8d1cd66",
      Green: "#EDF9EB",
      gradient: {
        start: "#D4A99D",
        end: "#1E5C5D",
      },
      accent: {
        gold: "#faa43c",           // Vibrant orange accent
      },
      tertiary: "#fae7e0",
      quaternary: "#F9F9F9",
      quinary: "#F0F0F0",
    },
    feedback: {
      success: "#22C55E",
      error: "#EF4444",
      warning: "#F59E0B",
      info: "#3B82F6",
      successBg: "#ECFDF5",
      errorBg: "#FEF2F2",
      warningBg: "#FFFBEB",
      infoBg: "#EFF6FF",
    },
    primary: {
      base: "#22875b",
      dark: "#1b6b49",
      light: "#4a9c6f",
      subtle: "#d6eaea",
    },
    secondary: {
      base: "#b58473",
      light: "#d4a99d",
    },
    accent: {
      gold: "#faa43c",
    },
    text: {
      primary: "#2f3e3f",
      secondary: "#6c8182",
      light: "#fbf7f0",
      onPrimary: "#fbf7f0",
    },
    border: {
      base: "#c6adad",
      subtle: "#ebeae8",
      primary: "#2f3e3f",
    },
    ui: {
      paper: "#fbf7f0",
      tape: "#ebeae8",
    },
  },
  font: {
    family: {
      base: 'Inter, "Helvetica Neue", Arial, sans-serif',
      heading: 'Montserrat, "Helvetica Neue", Arial, sans-serif',
      display: 'Playfair Display, serif',
    },
    size: {
      base: "1rem",
      sm: "0.875rem",
      md: "1.125rem",
      lg: "1.25rem",
      heading: {
        hero: "3.5rem",
        h1: "2.5rem",
        h2: "2rem",
        h3: "1.75rem",
        h4: "1.5rem",
        h5: "1.25rem",
        h6: "1rem",
      },
    },
    weight: {
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    lineHeight: {
      base: 1.6,
      heading: 1.2,
    },
  },
  card: {
    width: "400px",
    height: "500px",
    maxWidth: "100%",
    margin: "0 auto",
    alignSelf: "center",
    justifySelf: "center",
  },
  space: {
    0: "0px",
    2: "4px",
    4: "8px",
    8: "16px",
    12: "24px",
    16: "32px",
    24: "48px",
    32: "64px",
    48: "96px",
    64: "128px",
  },
  radius: {
    none: "0px",
    sm: "4px",
    md: "8px",
    lg: "16px",
    full: "50%",
  },
  shadow: {
    sm: "0 0 2px 1px rgba(0, 0, 0, 0.05)",
    md: "0 0 6px 2px rgba(0, 0, 0, 0.08)",
    lg: "0 0 12px 3px rgba(0, 0, 0, 0.12)",
    hover: "0 0 10px 2px rgba(0, 0, 0, 0.1)",
  },
  breakpoint: {
    sm: "480px",
    md: "768px",
    lg: "1024px",
    xl: "1280px",
    xxl: "1440px",
  },
  cursor: {
    pointer: "pointer",
    default: "default",
    notAllowed: "not-allowed",
    wait: "wait",
  },
  layout: {
    display: {
      inlineFlex: "inline-flex",
      block: "block",
      flex: "flex",
      grid: "grid",
    },
    center: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    align: {
      center: "center",
      start: "flex-start",
      end: "flex-end",
    },
    justify: {
      center: "center",
      between: "space-between",
      around: "space-around",
    },
  },
  spacing: {
    0: "0px",
    px: "1px",
    0.5: "2px",
    1: "4px",
    1.5: "6px",
    2: "8px",
    2.5: "10px",
    3: "12px",
    3.5: "14px",
    4: "16px",
    5: "20px",
    6: "24px",
    8: "32px",
    10: "40px",
    12: "48px",
    16: "64px",
    20: "80px",
    24: "96px",
    32: "128px",
    40: "160px",
    48: "192px",
    56: "224px",
    64: "256px",
  },
  grid: {
    columns: 12,
    gutter: "16px",
    maxWidth: "1280px",
  },
  typography: {
    fontFamily: {
      sans: '"Inter", system-ui, sans-serif',
      serif: '"Merriweather", serif',
      mono: '"Fira Code", monospace',
    },
    fontSize: {
      xs: "0.75rem",
      sm: "0.875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
    },
    fontWeight: {
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    lineHeight: {
      none: "1",
      tight: "1.25",
      snug: "1.375",
      normal: "1.5",
      relaxed: "1.625",
      loose: "2",
    },
    text: {
      decoration: {
        none: "none",
        underline: "underline",
        lineThrough: "line-through",
      },
    },
  },
  radii: {
    none: "0px",
    sm: "4px",
    md: "8px",
    lg: "12px",
    xl: "16px",
    full: "9999px",
  },
  shadows: {
    xs: "0 0 0 1px rgba(0,0,0,0.05)",
    sm: "0 1px 2px 0 rgba(0,0,0,0.05)",
    md: "0 4px 6px rgba(0,0,0,0.1)",
    lg: "0 10px 15px rgba(0,0,0,0.1)",
    xl: "0 20px 25px rgba(0,0,0,0.15)",
  },
  zIndex: {
    auto: "auto",
    0: 0,
    10: 10,
    20: 20,
    30: 30,
    40: 40,
    50: 50,
    dropdown: 100,
    header: 500,
    modal: 1000,
    tooltip: 1100,
  },
  breakpoints: {
    xs: "320px",
    sm: "640px",
    md: "768px",
    lg: "1024px",
    xl: "1280px",
    "2xl": "1536px",
  },
  maxWidth: {
    xs: "20rem",
    sm: "24rem",
    md: "28rem",
    lg: "32rem",
    xl: "36rem",
    "2xl": "42rem",
    "3xl": "48rem",
    full: "100%",
  },
  interactions: {
    transitions: {
      default: "all 150ms ease-in-out",
      fast: "all 75ms ease-in-out",
      slow: "all 300ms ease-in-out",
    },
    cursor: {
      pointer: "pointer",
      notAllowed: "not-allowed",
      wait: "wait",
      default: "default",
    },
    hover: {
      transform: "translateY(-1px)",
      filter: "brightness(1.05)",
      boxShadow: "0 6px 12px rgba(0, 0, 0, 0.1)",
    },
    active: {
      transform: "scale(0.98)",
      boxShadow: "0 2px 4px rgba(0, 0, 0, 0.08)",
    },
    focus: {
      ring: "focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-primary",
    },
  },
  transitionProperty: {
    all: "all",
    colors:
      "color, background-color, border-color, text-decoration-color, fill, stroke",
    opacity: "opacity",
    transform: "transform",
    shadow: "box-shadow",
    height: "height",
    width: "width",
    none: "none",
    default:
      "background-color, border-color, color, fill, stroke, opacity, box-shadow, transform",
  },
  aspectRatio: {
    square: "1 / 1",
    video: "16 / 9",
    golden: "1.618 / 1",
    portrait: "3 / 4",
    auto: "auto",
  },
  opacity: {
    none: 0,
    disabled: 0.5,
    overlay: 0.8,
    muted: 0.6,
    full: 1,
  },
  borderWidth: {
    none: "0px",
    hairline: "1px",
    thin: "2px",
    thick: "4px",
  },
  borderStyle: {
    solid: "solid",
    dashed: "dashed",
    dotted: "dotted",
  },
  states: {
    default: {
      background: "#F9FAFB",
      border: "#E5E7EB",
      text: "#111827",
    },
    hover: {
      background: "#E0F2FE",
      border: "#0EA5E9",
      text: "#111827",
    },
    active: {
      background: "#DBEAFE",
      border: "#1E40AF",
      text: "#111827",
    },
    disabled: {
      background: "#F3F4F6",
      border: "#D1D5DB",
      text: "#9CA3AF",
      opacity: 0.5,
    },
  },
  animations: {
    fadeIn: "fade-in 150ms ease-in-out",
    slideUp: "slide-up 300ms ease-out",
    bounce: "bounce 1s infinite",
    pulse: "pulse  2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
  },
  keyframes: {
    fadeIn: {
      from: { opacity: "0" },
      to: { opacity: "1" },
    },
    slideUp: {
      "0%": { transform: "translateY(100%)" },
      "100%": { transform: "translateY(0)" },
    },
    bounce: {
      "0%, 100%": {
        transform: "translateY(-25%)",
        animationTimingFunction: "cubic-bezier(0.8, 0, 1, 1)",
      },
      "50%": {
        transform: "translateY(0)",
        animationTimingFunction: "cubic-bezier(0, 0, 0.2, 1)",
      },
    },
    pulse: {
      "0%, 100%": { opacity: "1" },
      "50%": { opacity: "0.5" },
    },
  },
  transparencyOverlays: {
    light: "rgba(255, 255, 255, 0.6)",
    dark: "rgba(0, 0, 0, 0.5)",
    blurLight: "backdrop-blur-sm bg-white/60",
    blurDark: "backdrop-blur-sm bg-black/50",
  },
  iconSize: {
    sm: "16px",
    md: "20px",
    lg: "24px",
    xl: "32px",
  },
  size: {
    sm: "5rem",
    md: "24rem",
    lg: "32rem",
    xl: "40rem",
    full: "100%",
    auto: "auto",
  },
  height: {
    auto: "auto",
    sm: "20rem",
    md: "24rem",
    lg: "32rem",
    xl: "40rem",
    "2xl": "48rem",
    full: "100%",
    screen: "100vh",
    fit: "fit-content",
    min: "min-content",
    max: "max-content",
  },
  viewport: {
    fullHeight: "100vh",
    halfHeight: "50vh",
  },
  inset: {
    0: "0px",
    1: "0.25rem",
    2: "0.5rem",
    4: "1rem",
    8: "2rem",
    auto: "auto",
    "1/2": "50%",
    half: "50%",
    full: "100%",
    "-1": "-0.25rem",
    "-2": "-0.5rem",
    "-4": "-1rem",
  },
  gridTemplateColumns: {
    1: "repeat(1, minmax(0, 1fr))",
    2: "repeat(2, minmax(0, 1fr))",
    3: "repeat(3, minmax(0, 1fr))",
    4: "repeat(4, minmax(0, 1fr))",
    5: "repeat(5, minmax(0, 1fr))",
    6: "repeat(6, minmax(0, 1fr))",
    12: "repeat(12, minmax(0, 1fr))",
    sidebarMain: "300px 1fr",
  },
  motion: {
    duration: {
      instant: "50ms",
      fast: "150ms",
      medium: "300ms",
      slow: "500ms",
    },
    easing: {
      easeIn: "cubic-bezier(0.4, 0, 1, 1)",
      easeOut: "cubic-bezier(0, 0, 0.2, 1)",
      easeInOut: "cubic-bezier(0.4, 0, 0.2, 1)",
    },
  },
  layer: {
    base: 0,
    dropdown: 10,
    overlay: 20,
    modal: 30,
    toast: 40,
    tooltip: 50,
  },
  form: {
    borderColor: "#C6ADAD",
    focusColor: "#22875B",
    errorColor: "#DC2626",
    placeholderColor: "#9CA3AF",
  },
};

module.exports = { tokens };